'use client';

import Head from 'next/head';

export default function TermsAndConditionsPage() {
  return (
    <>
      <Head>
        <link rel="canonical" href="https://altpage.ai/terms-and-conditions" />
        <meta name="robots" content="index, follow" />
        <title>Terms and Conditions - AltPage.ai</title>
        <meta name="description" content="Terms and Conditions for AltPage.ai - AI-powered SEO page generation service by INTELICK PTE. LIMITED." />
      </Head>
      
      <div className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950 relative overflow-hidden">
        {/* 背景渐变效果 */}
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_#22d3ee15_0%,_transparent_60%)]"></div>
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_bottom_left,_#a78bfa15_0%,_transparent_60%)]"></div>
        
        <div className="max-w-4xl mx-auto px-6 py-12 relative z-10">
          <div className="prose prose-lg max-w-none">
            <h1 className="text-4xl font-bold mb-8 bg-gradient-to-r from-cyan-400 to-purple-500 text-transparent bg-clip-text">Terms and Conditions for AltPage.ai</h1>
            
            <p className="text-gray-300 leading-relaxed mb-8">
              Last Updated: 2025-05-27
            </p>

            <p className="text-gray-300 leading-relaxed mb-8">
              Welcome to AltPage.ai, the AI-powered SEO page generation service provided by INTELICK PTE. LIMITED ("we," "us," or "our"). These Terms and Conditions (the "Terms") govern your access to and use of AltPage.ai. By accessing or using AltPage.ai, you agree to be bound by these Terms. If you do not agree with any of these Terms, please do not use our service.
            </p>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">1. Definitions</h2>
              <div className="space-y-4">
                <p className="text-gray-300 leading-relaxed">
                  <strong className="text-white">AltPage.ai:</strong> Refers to our AI-driven platform provided by INTELICK PTE. LIMITED, which generates SEO-optimized web pages and related content.
                </p>
                <p className="text-gray-300 leading-relaxed">
                  <strong className="text-white">Service:</strong> The AltPage.ai service, including all features, functionalities, and any related software or content provided to you.
                </p>
                <p className="text-gray-300 leading-relaxed">
                  <strong className="text-white">User:</strong> Any individual or organization that accesses or uses AltPage.ai.
                </p>
                <p className="text-gray-300 leading-relaxed">
                  <strong className="text-white">Account:</strong> An account that you create to access and manage your subscription, billing, and usage of AltPage.ai.
                </p>
                <p className="text-gray-300 leading-relaxed">
                  <strong className="text-white">Content:</strong> Any text, images, or other data generated by or submitted through AltPage.ai.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">2. Service Description</h2>
              <p className="text-gray-300 leading-relaxed">
                AltPage.ai is an AI-driven tool designed to help users generate SEO-optimized content for web pages quickly and efficiently. While our service leverages advanced artificial intelligence technology, it is the User's responsibility to review and edit the generated content to ensure it meets all accuracy, compliance, and quality standards required for its intended use.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">3. Account Registration and Security</h2>
              <div className="space-y-6">
                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Registration</h3>
                  <p className="text-gray-300 leading-relaxed">
                    To use AltPage.ai, you may be required to register for an Account. You agree to provide accurate, complete, and current information during the registration process.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Security</h3>
                  <p className="text-gray-300 leading-relaxed">
                    You are responsible for safeguarding your Account credentials and for all activities that occur under your Account. Please notify us immediately if you suspect any unauthorized use of your Account.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Termination</h3>
                  <p className="text-gray-300 leading-relaxed">
                    We reserve the right to suspend or terminate your Account at our discretion, especially if we suspect any violation of these Terms.
                  </p>
                </div>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">4. Subscription, Payment, and Refund Policy</h2>
              <div className="space-y-6">
                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Subscription Plans</h3>
                  <p className="text-gray-300 leading-relaxed">
                    AltPage.ai is offered on a subscription basis. Detailed information about our subscription plans, pricing, and included features is available at: https://altpage.ai/pricing.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Payment</h3>
                  <p className="text-gray-300 leading-relaxed">
                    By subscribing to AltPage.ai, you agree to pay all applicable fees as specified in your selected subscription plan. All payments are processed securely via third-party payment platforms.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Refunds</h3>
                  <p className="text-gray-300 leading-relaxed">
                    Please refer to our pricing page for the details on our cancellation, refund policies, and any trial period information. Certain fees may be non-refundable as outlined in our policy.
                  </p>
                </div>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">5. User Obligations and Prohibited Activities</h2>
              <div className="space-y-6">
                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Lawful Use</h3>
                  <p className="text-gray-300 leading-relaxed">
                    You agree to use AltPage.ai only for lawful purposes and in compliance with these Terms.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Prohibited Activities</h3>
                  <p className="text-gray-300 leading-relaxed">
                    You must not use AltPage.ai to engage in any activity that is illegal, harmful, or violates any applicable laws or regulations. This includes any attempts to disrupt, disable, or otherwise interfere with the proper functioning of AltPage.ai.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">AI-Generated Content</h3>
                  <p className="text-gray-300 leading-relaxed">
                    As AltPage.ai uses artificial intelligence to generate content, inaccuracies or errors may occur. You are solely responsible for reviewing, editing, and ensuring that the generated content meets your specific needs and complies with all applicable laws.
                  </p>
                </div>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">6. Intellectual Property</h2>
              <div className="space-y-6">
                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Ownership</h3>
                  <p className="text-gray-300 leading-relaxed">
                    All materials provided through AltPage.ai, including software, documentation, and other proprietary materials (except for content provided by Users), are owned by INTELICK PTE. LIMITED or its licensors and are protected by intellectual property laws.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">User-Generated Content</h3>
                  <p className="text-gray-300 leading-relaxed">
                    You retain ownership of any content that you upload or input into AltPage.ai. However, by using AltPage.ai, you grant INTELICK PTE. LIMITED a worldwide, non-exclusive, royalty-free license to use, store, and process such content solely for the purpose of providing and improving the Service.
                  </p>
                </div>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">7. Disclaimer and Limitation of Liability</h2>
              <div className="space-y-6">
                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Disclaimer</h3>
                  <p className="text-gray-300 leading-relaxed">
                    AltPage.ai is provided on an "as is" and "as available" basis without any warranties, either express or implied. INTELICK PTE. LIMITED does not warrant that the Service will be uninterrupted, error-free, or secure.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">AI-Generated Content Disclaimer</h3>
                  <p className="text-gray-300 leading-relaxed">
                    The content generated by AltPage.ai is for informational purposes only. Given the nature of AI technology, the generated content may contain errors or inaccuracies. It is your responsibility to verify and modify the content as necessary, and you assume full responsibility for its use.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Limitation of Liability</h3>
                  <p className="text-gray-300 leading-relaxed">
                    To the fullest extent permitted by law, INTELICK PTE. LIMITED shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from or related to your use of AltPage.ai, even if advised of the possibility of such damages.
                  </p>
                </div>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">8. Indemnification</h2>
              <p className="text-gray-300 leading-relaxed">
                You agree to indemnify, defend, and hold harmless INTELICK PTE. LIMITED, its affiliates, and their respective officers, directors, employees, and agents from any claims, damages, losses, liabilities, costs, or expenses (including reasonable attorneys' fees) arising from your violation of these Terms or your use of AltPage.ai.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">9. Termination</h2>
              <div className="space-y-6">
                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">By Us</h3>
                  <p className="text-gray-300 leading-relaxed">
                    INTELICK PTE. LIMITED reserves the right to suspend or terminate your access to AltPage.ai at any time, with or without notice, for any reason including violations of these Terms.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">By You</h3>
                  <p className="text-gray-300 leading-relaxed">
                    During the free trial period and after upgrading to a paid subscription, you may cancel your subscription at any time. If you cancel after the free trial period, the cancellation will take effect in the next billing cycle. Please refer to our refund policy on the pricing page for details regarding subscription cancellations and any potential refunds.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Effect of Termination</h3>
                  <p className="text-gray-300 leading-relaxed">
                    Upon termination, your right to use AltPage.ai will immediately cease. Any provisions of these Terms that are intended to survive termination will continue to be in effect.
                  </p>
                </div>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">10. Governing Law and Dispute Resolution</h2>
              <div className="space-y-6">
                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Governing Law</h3>
                  <p className="text-gray-300 leading-relaxed">
                    These Terms shall be governed by and construed in accordance with the laws of Singapore.
                  </p>
                </div>

                <div className="bg-white/5 backdrop-blur-sm border border-slate-700/50 rounded-lg p-6">
                  <h3 className="text-xl font-medium text-white mb-2">Dispute Resolution</h3>
                  <p className="text-gray-300 leading-relaxed">
                    Any disputes arising out of or relating to these Terms or AltPage.ai shall be exclusively resolved in the courts located in Singapore. By using AltPage.ai, you consent to the jurisdiction and venue of such courts.
                  </p>
                </div>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">11. Changes to These Terms</h2>
              <p className="text-gray-300 leading-relaxed">
                INTELICK PTE. LIMITED reserves the right to modify or update these Terms at any time. Any changes will be posted on this page and will be effective immediately upon posting. Your continued use of AltPage.ai following the posting of changes constitutes your acceptance of the updated Terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-cyan-400 mb-4">12. Contact Information</h2>
              <p className="text-gray-300 leading-relaxed mb-4">
                If you have any questions or concerns about these Terms, please contact us at: <a href="mailto:admin@intelick.com" className="text-cyan-400 hover:text-cyan-300 underline">admin@intelick.com</a>
              </p>
              <p className="text-gray-300 leading-relaxed mb-4">
                INTELICK PTE. LIMITED<br />
                Registered in Singapore
              </p>
              <p className="text-gray-300 leading-relaxed">
                By accessing or using AltPage.ai, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.
              </p>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}